[package]
name = "slate-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
clap = { version = "4.6.1", features = ["derive"] }
dioxus = { workspace = true, features = ["fullstack", "server"] }
serde_json = "1.0.149"
slate-bridge = { path = "../bridge" }
slate-client = { path = "../client", features = ["server"] }
tokio = { version = "1.52.3", features = ["io-std", "io-util", "macros", "net", "process", "rt-multi-thread", "time"] }
url = "2.5.8"
