[package]
name = "slate-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
dioxus = { workspace = true, features = ["fullstack", "server"] }
futures = "0.3.32"
notify = "8.2.0"
serde = { version = "1.0.228", features = ["derive"] }
slate-bridge = { path = "../bridge" }
tokio = "1.52.3"
slate-shared = { path = "../shared" }
