#import "vault.typ":*
#show: setup
#tag("analouge")

= Monostable Pulse Generator
A circuit that produces a single pulse of a fixed duration in response to an input trigger a diagram can be seen below

#circuit({
  import zap:*

  opamp("o1", (0, 0), variant: "ieee", fill: none, sign-stroke: white)

  resistor("rr", (-1.5, 0.45), (rel: (0, 2)), position: 60%, label: $R_r$)
  nstub("rr.out", label: $V_(r e f)$)

  capacitor("cc", "o1.minus", (rel: (-2, 0)), position: 90%)

  wstub("cc.out", label: $V_(i n)$)

  capacitor("c2", (1.5, 0), (rel: (0, -2)), label: $C_2$)

  resistor("r1", "c2.out", (rel: (0, -2)), label: $R_1$)
  wire("c2.in", "o1.out")

  resistor("r2", "r1.out", (rel: (0, -2)), label: $R_2$)

  zwire("r1.out", "o1.plus", ratio: 130%)

  earth("end", "r2.out")
})

The circuit attached to the input negative input converts any signal to a short pulse then floats back to $V_(r e f)$.

The capacitor $C_2$ means by default $V_+$ is at 0V, but when a pulse comes in it will slowly raise to $V_(r e f)$ creating a fixed width pulse.

The period of this pulse is $T = R C ln(frac(2 beta V_s, V_r))$

#flashcard("What does an monostable pulse generator do?", "Generates a fixed length pulse from a signal")
#flashcard("What is the period of the pulse generated by a monostable pulse generator?", "T = R C ln(2 V_s beta / V_r)")
#flashcard(
  "Describe the circuit of a monostable pulse generator",
  "
#circuit({
  import zap: *

  opamp(\"o1\", (0, 0), variant: \"ieee\", fill: none, sign-stroke: white)

  resistor(\"rr\", (-1.5, 0.45), (rel: (0, 2)), position: 60%, label: $R_r$)
  nstub(\"rr.out\", label: $V_(r e f)$)

  capacitor(\"cc\", \"o1.minus\", (rel: (-2, 0)), position: 90%)

  wstub(\"cc.out\", label: $V_(i n)$)

  capacitor(\"c2\", (1.5, 0), (rel: (0, -2)), label: $C_2$)

  resistor(\"r1\", \"c2.out\", (rel: (0, -2)), label: $R_1$)
  wire(\"c2.in\", \"o1.out\")

  resistor(\"r2\", \"r1.out\", (rel: (0, -2)), label: $R_2$)

  zwire(\"r1.out\", \"o1.plus\", ratio: 130%)

  earth(\"end\", \"r2.out\")
})
",
)